@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DoctorBaseParser" as DoctorBaseParser LOGIC_COLOR
participant ":AddAppointmentCommandParser" as AddAppointmentCommandParser LOGIC_COLOR
participant "a:AddAppointmentCommand" as AddAppointmentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

-> LogicManager : execute("add-appt 1 t/DentalCheckup dt/10-10-2010, 0900")
activate LogicManager

LogicManager -> DoctorBaseParser : parseCommand("add-appt 1 at/DentalCheckup ad/10-10-2010, 0900")
activate DoctorBaseParser

create AddAppointmentCommandParser
DoctorBaseParser -> AddAppointmentCommandParser
activate AddAppointmentCommandParser

AddAppointmentCommandParser --> DoctorBaseParser
deactivate AddAppointmentCommandParser

DoctorBaseParser -> AddAppointmentCommandParser : parse("1 at/DentalCheckup ad/10-10-2010, 0900")
activate AddAppointmentCommandParser

create AddAppointmentCommand
AddAppointmentCommandParser -> AddAppointmentCommand
activate AddAppointmentCommand

AddAppointmentCommand --> AddAppointmentCommandParser :
deactivate AddAppointmentCommand

AddAppointmentCommandParser --> DoctorBaseParser : a
deactivate AddAppointmentCommandParser

AddAppointmentCommandParser -[hidden]-> DoctorBaseParser
destroy AddAppointmentCommandParser

DoctorBaseParser --> LogicManager : a
deactivate DoctorBaseParser

LogicManager -> AddAppointmentCommand : execute(m)
activate AddAppointmentCommand

AddAppointmentCommand -> Model : setPatient(targetPatient, newPatient)
activate Model
Model --> AddAppointmentCommand
deactivate Model

create CommandResult
AddAppointmentCommand -> CommandResult
activate CommandResult

CommandResult --> AddAppointmentCommand
deactivate CommandResult

AddAppointmentCommand --> LogicManager : r
deactivate AddAppointmentCommand

<-- LogicManager
deactivate LogicManager
@enduml
