@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

DoctorBase *-right-> "1" UniquePatientList
UniquePatientList -right-> Patient
Patient -up-> "1" MedicalHistory

MedicalHistory *-right-> "*" PastMedicalRecords

Patient *--> Name
Patient *--> Nric
Patient *--> Gender
Patient *--> Phone
Patient *--> Email
Patient *--> DateOfBirth
Patient *--> Address
@enduml
