@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

DoctorBase *-right-> "1" UniquePatientList
UniquePatientList -right-> Patient
DoctorBase *-right-> "*" UniqueMedicalHistoryList
UniqueMedicalHistoryList -right-> MedicalHistory
Patient -up-> "1" MedicalHistory
Patient *--> Name
Patient *--> Nric
Patient *--> Gender
Patient *--> Phone
Patient *--> Email
Patient *--> DateOfBirth
Patient *--> Address

Patient -down-> "*" Appointment
Appointment *--> Title
Appointment *--> LocalDateTime
@enduml
