@startuml
!include style.puml
start
:Receive user input;
:Parse index from preamble;
if () then ([valid index])
    :Parse index;
    :Create DeleteAppointmentCommand;
    stop
else ([else])
    :Throw ParseException
    (invalid index);
    stop
@enduml
