@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":DoctorBaseParser" as DoctorBaseParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> DoctorBaseParser : parseCommand("delete 1")
activate DoctorBaseParser

create DeleteCommandParser
DoctorBaseParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> DoctorBaseParser
deactivate DeleteCommandParser

DoctorBaseParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser :
deactivate DeleteCommand

DeleteCommandParser --> DoctorBaseParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> DoctorBaseParser
destroy DeleteCommandParser

DoctorBaseParser --> LogicManager : d
deactivate DoctorBaseParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : deletePatient(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

<--LogicManager
deactivate LogicManager
@enduml
